//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.12 at 11:01:54 PM IDT 
//


package engine.enigma.jaxb_classes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the app.temp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: app.temp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CTEEnigma }
     * 
     */
    public CTEEnigma createCTEEnigma() {
        return new CTEEnigma();
    }

    /**
     * Create an instance of {@link CTEMachine }
     * 
     */
    public CTEMachine createCTEMachine() {
        return new CTEMachine();
    }

    /**
     * Create an instance of {@link CTERotors }
     * 
     */
    public CTERotors createCTERotors() {
        return new CTERotors();
    }

    /**
     * Create an instance of {@link CTERotor }
     * 
     */
    public CTERotor createCTERotor() {
        return new CTERotor();
    }

    /**
     * Create an instance of {@link CTEPositioning }
     * 
     */
    public CTEPositioning createCTEPositioning() {
        return new CTEPositioning();
    }

    /**
     * Create an instance of {@link CTEReflectors }
     * 
     */
    public CTEReflectors createCTEReflectors() {
        return new CTEReflectors();
    }

    /**
     * Create an instance of {@link CTEReflector }
     * 
     */
    public CTEReflector createCTEReflector() {
        return new CTEReflector();
    }

    /**
     * Create an instance of {@link CTEReflect }
     * 
     */
    public CTEReflect createCTEReflect() {
        return new CTEReflect();
    }

    /**
     * Create an instance of {@link CTEDecipher }
     * 
     */
    public CTEDecipher createCTEDecipher() {
        return new CTEDecipher();
    }

    /**
     * Create an instance of {@link CTEDictionary }
     * 
     */
    public CTEDictionary createCTEDictionary() {
        return new CTEDictionary();
    }

    /**
     * Create an instance of {@link CTEBattlefield }
     * 
     */
    public CTEBattlefield createCTEBattlefield() {
        return new CTEBattlefield();
    }

}
